<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Generator as Faker;
use Illuminate\Support\Facades\Storage;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(Faker $faker): void
    {
        $directory = [
            ['name' => "Shish Tawook", 'price' => 890,],
            ['name' => "Lamb Chops", 'price' => 1050,],
            ['name' => "Kebbey (Meat Balls)", 'price' => 700,],
            ['name' => "Babaganoush Dip", 'price' => 690,],
            ['name' => "Spicy Hummus Dip", 'price' => 980,],
            ['name' => "Mutabal", 'price' => 750,],
            ['name' => "Lebanese Special Platter", 'price' => 3900,],
            ['name' => "Joja Kabab Platter", 'price' => 3100,],
            ['name' => "Peach Margarita", 'price' => 400,],
            ['name' => "Mint Margarita", 'price' => 300,],
            ['name' => "Mint Lemonade", 'price' => 250,],
            ['name' => "Fresh Lime and 7up", 'price' => 190,],
            ['name' => "Strawberry Mojito", 'price' => 350,],
            ['name' => "Pina Colada", 'price' => 450,],
            ['name' => "Soft Drinks", 'price' => 100,],
            ['name' => "Mineral Water Small", 'price' => 85,],
            ['name' => "Mineral Water Large", 'price' => 130,],
            ['name' => "Dood Pati", 'price' => 200,],
            ['name' => "Karak Chaaye", 'price' => 180,],
            ['name' => "Espresso", 'price' => 220,],
            ['name' => "Cappuccino", 'price' => 350,],
            ['name' => "Mocca Chino", 'price' => 420,],
            ['name' => "Americano", 'price' => 250,],
            ['name' => "Plain Naan", 'price' => 40,],
            ['name' => "Roghni Naan", 'price' => 50,],
            ['name' => "Garlic Naan", 'price' => 80,],
            ['name' => "Laal Roti", 'price' => 40,],
            ['name' => "Fried Chicken Wings", 'price' => 450,],
            ['name' => "Finger Fish", 'price' => 1000,],
            ['name' => "Honey Wings", 'price' => 500,],
            ['name' => "Dynamite Chicken", 'price' => 670,],
            ['name' => "Crispy Chicken Strips and Chips ", 'price' => 1200,],
            ['name' => "Plain Fries", 'price' => 300,],
            ['name' => "Plain Fries (Masala)", 'price' => 380,],
            ['name' => "Plain Fries (Cheese)", 'price' => 480,],
            ['name' => "Plain Fries (Swiss Mushroom)", 'price' => 500,],
            ['name' => "Plain Fries (Pizza Sauce)", 'price' => 470,],
            ['name' => "Plain Fries (Jalapeno Sauce)", 'price' => 400,],
            ['name' => "Hot and Sour Soup (Single Bowl)", 'price' => 250,],
            ['name' => "Hot and Sour Soup (Family Bowl)", 'price' => 850,],
            ['name' => "Thai Soup (Single Bowl)", 'price' => 250,],
            ['name' => "Thai Soup (Family Bowl)", 'price' => 850,],
            ['name' => "Tom Yom Soup  (Single Bowl)", 'price' => 350,],
            ['name' => "Tom Yom Soup  (Family Bowl)", 'price' => 1300,],
            ['name' => "Chicken Corn Soup (Single Bowl)", 'price' => 250,],
            ['name' => "Chicken Corn Soup (Family Bowl)", 'price' => 850,],
            ['name' => "Cream Mushroom Soup (Single Bowl)", 'price' => 250,],
            ['name' => "Cream Mushroom Soup (Family Bowl)", 'price' => 850,],
            ['name' => "Cream of Chicken Soup (Single Bowl)", 'price' => 250,],
            ['name' => "Cream of Chicken Soup (Family Bowl)", 'price' => 850,],
            ['name' => "Lebanese Mezze Platter", 'price' => 1000,],
            ['name' => "Caesar Salad", 'price' => 600,],
            ['name' => "Russian Salad", 'price' => 750,],
            ['name' => "Pasta Salad", 'price' => 400,],
            ['name' => "Beans Salad", 'price' => 300,],
            ['name' => "Fresh Greens Salad", 'price' => 200,],
            ['name' => "Lentil Soup (Single Bowl)", 'price' => 200,],
            ['name' => "Lentil Soup (Family Bowl)", 'price' => 750,],
            ['name' => "Greek Salad", 'price' => 500,],
            ['name' => "Fattoush", 'price' => 350,],
            ['name' => "Lebanese Salad", 'price' => 650,],
            ['name' => "Falafel", 'price' => 800,],
            ['name' => "Beef Shawarma", 'price' => 690,],
            ['name' => "Shish Tawook Shawarma", 'price' => 690,],
            ['name' => "Hummus Mah Lahme", 'price' => 1050,],
            ['name' => "Shawarma Plate", 'price' => 1150,],
            ['name' => "Falafel Plate", 'price' => 1250,],
            ['name' => "Kung Pow Chicken (Half)", 'price' => 1150,],
            ['name' => "Kung Pow Chicken (Full)", 'price' => 2100,],
            ['name' => "Chicken with Cashew Nuts (Half)", 'price' => 1075,],
            ['name' => "Chicken with Cashew Nuts (Full)", 'price' => 1950,],
            ['name' => "Chicken with Almond (Half)", 'price' => 1100,],
            ['name' => "Chicken with Almond (Full)", 'price' => 2000,],
            ['name' => "Chicken with Pineapple (Half)", 'price' => 1000,],
            ['name' => "Chicken with Pineapple (Full)", 'price' => 1900,],
            ['name' => "Mongolian Chicken (Half)", 'price' => 900,],
            ['name' => "Mongolian Chicken (Full)", 'price' => 1700,],
            ['name' => "Black Pepper Chicken (Half)", 'price' => 1100,],
            ['name' => "Black Pepper Chicken (Full)", 'price' => 2100,],
            ['name' => "Chicken Manchurian (Half)", 'price' => 1000,],
            ['name' => "Chicken Manchurian (Full)", 'price' => 1900,],
            ['name' => "Chicken Chilli Dry (Half)", 'price' => 925,],
            ['name' => "Chicken Chilli Dry (Full)", 'price' => 1650,],
            ['name' => "Chicken Chowmein", 'price' => 950,],
            ['name' => "Beef Chowmein", 'price' => 990,],
            ['name' => "Vegetable Chowmein", 'price' => 600,],
            ['name' => "Lasagna", 'price' => 1290,],
            ['name' => "Chicken Alfredo Pasta", 'price' => 1250,],
            ['name' => "Baked Rigatoni Creamy Pasta", 'price' => 1300,],
            ['name' => "Fish Fillet", 'price' => 1100,],
            ['name' => "Grilled Fish with Saffron Sauce", 'price' => 1450,],
            ['name' => "Fish and Chips", 'price' => 1290,],
            ['name' => "Chicken Ala Kiev", 'price' => 980,],
            ['name' => "Chicken Tikka Pizza (Medium)", 'price' => 1490,],
            ['name' => "Chicken Tikka Pizza (Large)", 'price' => 2090,],
            ['name' => "Chicken Fajita Pizza (Medium)", 'price' => 1490,],
            ['name' => "Chicken Fajita Pizza (Large)", 'price' => 2090,],
            ['name' => "Crown Crust Pizza (Medium)", 'price' => 1600,],
            ['name' => "Crown Crust Pizza (Large)", 'price' => 2200,],
            ['name' => "Pepper Corn Steak", 'price' => 1490,],
            ['name' => "Mushroom Steak ", 'price' => 1490,],
            ['name' => "Mexican Steak", 'price' => 1890,],
            ['name' => "Twin Steak", 'price' => 1590,],
            ['name' => "French Onion Steak", 'price' => 1650,],
            ['name' => "Jalapeno Beef Burger", 'price' => 750,],
            ['name' => "Grilled Beef Burger", 'price' => 750,],
            ['name' => "Stuffed Chicken Burger", 'price' => 650,],
            ['name' => "Zinger Burger", 'price' => 650,],
            ['name' => "Chicken Crunch Burger", 'price' => 500,],
            ['name' => "Double Decker Club Sandwich", 'price' => 650,],
            ['name' => "Grilled Chicken Sandwich", 'price' => 880,],
            ['name' => "Make it a Meal (French Fries & Soft Drink)", 'price' => 250,],
            ['name' => "BeefChili Dry (Half)", 'price' => 1050,],
            ['name' => "BeefChili Dry (Full)", 'price' => 1900,],
            ['name' => "Mangolian Beef(Half)", 'price' => 1100,],
            ['name' => "Mangolian Beef (Full)", 'price' => 2000,],
            ['name' => "Stir Fry Beef Chilli (Half)", 'price' => 1150,],
            ['name' => "Stir Fry Beef Chilli (Full)", 'price' => 2200,],
            ['name' => "Chlli Oyster Beef (Half)", 'price' => 1300,],
            ['name' => "Chlli Oyster Beef (Full) ", 'price' => 2450,],
            ['name' => "Hot & Spicy Braised Beef (Half)", 'price' => 1150,],
            ['name' => "Hot & Spicy Braised Beef (Full)", 'price' => 2250,],
            ['name' => "Egg Fried Rice", 'price' => 850,],
            ['name' => "Chicken Fried Rice", 'price' => 1100,],
            ['name' => "Vegetable Rice", 'price' => 850,],
            ['name' => "Garlic Rice", 'price' => 750,],
            ['name' => "Seekh Kabab Karahi (Half)", 'price' => 1100,],
            ['name' => "Seekh Kabab Karahi (Full)", 'price' => 2000,],
            ['name' => "Chapli Kabab", 'price' => 450,],
            ['name' => "Mutton Afghani Pulao", 'price' => 2400,],
            ['name' => "Bannu Beef Pulao", 'price' => 1350,],
            ['name' => "Chicken Biryani", 'price' => 1100,],
            ['name' => "Peas Pulao", 'price' => 550,],
            ['name' => "Palak Paneer (Half)", 'price' => 600,],
            ['name' => "Palak Paneer (Full)", 'price' => 1100,],
            ['name' => "Daal Mash (Half)", 'price' => 550,],
            ['name' => "Daal Mash (Full)", 'price' => 1000,],
            ['name' => "Shahi Daal (Half)", 'price' => 600,],
            ['name' => "Shahi Daal (Full)", 'price' => 1090,],
            ['name' => "Mian Jee Kee Daal (Half)", 'price' => 800,],
            ['name' => "Mian Jee Kee Daal (Full)", 'price' => 1500,],
            ['name' => "Chicken Makhni Karahi (Half)", 'price' => 1050,],
            ['name' => "Chicken Makhni Karahi (Full)", 'price' => 1950,],
            ['name' => "Chicken Namkeen Karahi (Half)", 'price' => 950,],
            ['name' => "Chicken Namkeen Karahi (Full)", 'price' => 1700,],
            ['name' => "Green Chilli Chicken Karahi (Half)", 'price' => 950,],
            ['name' => "Green Chilli Chicken Karahi (Full)", 'price' => 1700,],
            ['name' => "Arabian Chicken Handi (Half)", 'price' => 1150,],
            ['name' => "Arabian Chicken Handi (Full)", 'price' => 2200,],
            ['name' => "Chicken White Handi (Half)", 'price' => 1150,],
            ['name' => "Chicken White Handi (Full)", 'price' => 2200,],
            ['name' => "Chicken Achari (Half)", 'price' => 1000,],
            ['name' => "Chicken Achari (Full)", 'price' => 1800,],
            ['name' => "Shenwari Mutton Karahi (Half)", 'price' => 1650,],
            ['name' => "Shenwari Mutton Karahi (Full)", 'price' => 3100,],
            ['name' => "Peshawri Namkeen Mutton Karahi (Half)", 'price' => 1600,],
            ['name' => "Peshawri Namkeen Mutton Karahi (Full)", 'price' => 3000,],
            ['name' => "Balochi Mutton Karahi (Half)", 'price' => 1700,],
            ['name' => "Balochi Mutton Karahi (Full)", 'price' => 3200,],
            ['name' => "Mutton Handi (Half)", 'price' => 1750,],
            ['name' => "Mutton Handi (Full)", 'price' => 3300,],
            ['name' => "Mutton Joint / Rosh", 'price' => 1000,],
            ['name' => "Chicken Malai Boti (Boneless)", 'price' => 650,],
            ['name' => "Chicken Tikka", 'price' => 500,],
            ['name' => "Chicken Tikka Boti ", 'price' => 500,],
            ['name' => "Beef Behari Boti", 'price' => 550,],
            ['name' => "Fish Tikka", 'price' => 740,],
            ['name' => "Beef Gola Kabab", 'price' => 550,],
            ['name' => "Mutton Chops", 'price' => 1000,],
            ['name' => "Seekh Kabab", 'price' => 650,],
            ['name' => "Reshmi Kabab", 'price' => 550,],
            ['name' => "BBQ Platter (Half)", 'price' => 2600,],
            ['name' => "BBQ Platter (Full)", 'price' => 7500,],
            ['name' => "Shahi Platter (Half)", 'price' => 5000,],
            ['name' => "Shahi Platter (Full)", 'price' => 14000,],
            ['name' => "Spanish Flan", 'price' => 400,],
            ['name' => "Mango Moose", 'price' => 430,],
            ['name' => "Molten Lava", 'price' => 600,],
            ['name' => "Gajrela (Bowl)", 'price' => 450,],
            ['name' => "Mix Kheer", 'price' => 550,],
            ['name' => "Gulab Jamun", 'price' => 300,],
            ['name' => "Ras Malai", 'price' => 360,],
            ['name' => "Sizzling Brownie with Ice Cream", 'price' => 400,],
            ['name' => "Ice Cream (2 Scoops)", 'price' => 270,],
            ['name' => "Ice Cream (3 Scoops)", 'price' => 400,],
            ['name' => "Pineapple Crunch", 'price' => 950,],
            ['name' => "American Coffee", 'price' => 300,],
            ['name' => "Expresso", 'price' => 250,],
            ['name' => "Cold Coffee", 'price' => 450,],
            ['name' => "Cold Coffee With Ice Cream", 'price' => 480,],
            ['name' => "Hot Chocolate", 'price' => 350,],
            ['name' => "Latte Coffee", 'price' => 350,],
            ['name' => "Green Tea & Lemon Or Mint", 'price' => 90,],
            ['name' => "Sulemani Tea", 'price' => 90,],
            ['name' => "Spiced Honey Wings (6 Piece)", 'price' => 550,],
            ['name' => "French Fries", 'price' => 300,],
            ['name' => "Greek Feta Cheese Salad", 'price' => 500,],
            ['name' => "Chef Salad", 'price' => 700,],
            ['name' => "Hawaiian Salad", 'price' => 700,],
            ['name' => "Chicken Panini Sandwich (2 Pcs)", 'price' => 500,],
            ['name' => "Grilled Beef Panini Sandwich (2 Pcs)", 'price' => 580,],
            ['name' => "Club Beef Burger", 'price' => 450,],
            ['name' => "Chicken Burger", 'price' => 400,],
            ['name' => "Barbeque Burger", 'price' => 500,],
            ['name' => "Philly Cheese Steak Sandwich", 'price' => 590,],
            ['name' => "Special Zinger Burger", 'price' => 650,],
            ['name' => "Bakers Street Club Sandwich", 'price' => 500,],
            ['name' => "Chicken Sandwich", 'price' => 400,],
            ['name' => "Chicken Parmesan", 'price' => 750,],
            ['name' => "Pane Bolognese", 'price' => 700,],
            ['name' => "Alfredo Pasta", 'price' => 700,],
            ['name' => "Pizza au Tandoori (Medium)", 'price' => 1490,],
            ['name' => "Pizza au Tandoori (Large)", 'price' => 2090,],
            ['name' => "Chicken Patties", 'price' => 100,],
            ['name' => "Chocolate Brownie", 'price' => 100,],
            ['name' => "Walnut Brownie ", 'price' => 100,],
            ['name' => "Date & Almond", 'price' => 120,],
            ['name' => "Basbousa", 'price' => 80,],
            ['name' => "Mini Pizza", 'price' => 120,],
            ['name' => "Lemon Tart", 'price' => 100,],
            ['name' => "Walnut Tart", 'price' => 180,],
            ['name' => "Chocolate Eclairs", 'price' => 170,],
            ['name' => "Doughnut", 'price' => 190,],
            ['name' => "Cup Cake", 'price' => 90,],
            ['name' => "Banana Bread", 'price' => 80,],
            ['name' => "Lemon Cake", 'price' => 60,],
            ['name' => "Cream Roll", 'price' => 120,],
            ['name' => "Cinnamon Roll", 'price' => 200,],
            ['name' => "Raisin Bread", 'price' => 130,],
            ['name' => "Assorted Milkshake", 'price' => 400,],
            ['name' => "Large Bread", 'price' => 200,],
            ['name' => "Cake", 'price' => 1750,],
            ['name' => "Biscuits", 'price' => 200,],
            ['name' => "Biscuits Half KG", 'price' => 600,],
            ['name' => "Biscuits 1 KG", 'price' => 1200,],
            ['name' => "Cake Rusk", 'price' => 600,],
            ['name' => "Raita", 'price' => 80,],
            ['name' => "Lays", 'price' => 80,],
            ['name' => "Pakoras", 'price' => 400,],
            ['name' => "Fresh Apple Juice", 'price' => 300,],
            ['name' => "Special Elaichi Tea", 'price' => 180,],
            ['name' => "Paratha", 'price' => 130,],
            ['name' => "Breakfast", 'price' => 550,],
            ['name' => "Chicken Garlic Mayo Roll", 'price' => 0,],
            ['name' => "Chicken Chatni Roll", 'price' => 0,],
            ['name' => "Malai Boti Roll", 'price' => 0,],
            ['name' => "Gol Gappay", 'price' => 0,],
            ['name' => "Dahi Phulki", 'price' => 0,],
            ['name' => "Chicken Sajji", 'price' => 0,],
        ];


        foreach ($directory as $productSpecimen) {
            // dd($productSpecimen);

            Product::updateOrCreate([
                'name' => $productSpecimen['name'],
                // 'description' => $productSpecimen->make,
                // 'category' => $productSpecimen->category,
                // 'image' => "images/{$imageName}",
                'barcode' => $faker->ean13(),
                'price' => $productSpecimen['price'],
                'quantity' => '99',
                'aval_status' => true,
            ]);
        }
    }
}
// {"name":"971 Gajjar Halwa Full","price":1500,"category":"Dessert","make":"Pakistani"}


// $table->string('name');
// $table->text('description')->nullable();
// $table->text('category')->nullable();
// $table->string('image')->nullable();
// $table->string('barcode')->unique();
// $table->decimal('price', 8, 2);
// $table->boolean('status')->default(true);

// 'name',
//         'description',
//         'image',
//         'barcode',
//         'price',
//         'quantity',
//         'status',
//         'category'